### ISSUE TITLE
External script files will not be created if HtmlExternalScriptsCdn is set

### ISSUE THREAD

**Issue by tschoeck** [baaron4/GW2-Elite-Insights-Parser#547] opened 2021-03-01 20:03 UTC
https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/c6c358e0816d54c6942358c3cfaf8a3b0a5a377b/GW2EIBuilders/HTMLBuilder.cs#L69-L94

https://github.com/baaron4/GW2-Elite-Insights-Parser/blob/c6c358e0816d54c6942358c3cfaf8a3b0a5a377b/GW2EIBuilders/HTMLBuilder.cs#L162-L190

If the HtmlExternalScriptsCdn is set, the external script files will never be written to HtmlExternalScriptsPath. The original code I submitted was set to this order of logic:

1. if there is a custom directory set for external script files, create files there, if the target directory exists or can be created
2. dont write those exact files (with version number) if they already exist
3. if externalcdnpath is set, use it for including in the html output

The info about the externalscriptpath not being used if the cdn path is set does only apply to the including itself.

So now, because of the return if CdnPath is set, the external script files will never be written to target directory. 
A workaround for this until next fix is to once not set the cdn path, create one report, then set the cdnpath again. in this case those files will be at externalscriptpath location and the including works.

Do you want me to submit another pull request for this?

**Comment by EliphasNUIT** [comment] 2021-03-03 00:33
If my understanding is correct, you want the file to be generated, if not present, even if we don't use it?

**Comment by tschoeck** [comment] 2021-03-03 19:18
OK let me explain. I see two different possibilities to use the cdn feature:

1) You host a webservice. So the idea here is that the external scripts are always created if not present. Especially after you patch to a new ei version. So the files get placed in a dictionary you have published for the web. for example: static.your-address.com points to local dictionary at C:\static on the server. you want the external script files to be placed there if not existing because the cdn link will load those files from there.

why use a different path even if the files are located on the same server? The answer is needed space for each report.

2) you want to use an external cdn server somewhere, hosted by you or any other person. therefor you have to trust those files are there and dont need to generate them locally

My bug report points to option 1 obviously.

But as I write this I see what you mean, You could leave the feature like it is, but as an admin you would have to copy those external files to the static dictionary manually everytime there was an update for ei

**Comment by EliphasNUIT** [comment] 2021-03-05 17:04
Okay, I understand your point better, I didn't get that there was explicit intent to generate the files when both are set but it does make sense and I think your use case would be the most common one. I'll change it.

**Comment by EliphasNUIT** [comment] 2021-03-05 21:55
Added in b45aa13c9abc0691cb0538ddcca03d2e78c3c619.

**Comment by aeris** [comment] 2021-05-18 13:58
I reopen this bug because b45aa13 seems introduce a regression.
This feature is no more usable in 2.34.1.0, setting `HtmlExternalScriptsPath=./html/` with `HtmlExternalScriptsCdn=/gw2/` generate files on the right local folder `./html/EliteInsights-2.34.1.js` but in the generated HTML, you also have this `./html/` instead of the expected `/gw2/` : `<link rel="stylesheet" type="text/css" href="./html/EliteInsights-2.34.1.css?version=0">`

**Comment by EliphasNUIT** [comment] 2021-05-18 15:10
It seems it only works on debug mode, I see what's wrong.

**Comment by EliphasNUIT** [comment] 2021-05-18 15:14
Should be fixed in c071edb5ad559c6453c5ab447f830ec2598384ab.

**Closed** 2021-06-27 19:44 UTC
Labels: enhancement
