### ISSUE TITLE
Automatically adding new logs not working with arcdps created logs

### ISSUE THREAD

**Issue by NekoSojo** [baaron4/GW2-Elite-Insights-Parser#491] opened 2020-08-28 18:32 UTC
The parser dose not seem to see newly created EVTC logs created by ArcDPS. If I copy the file or move a file into the file folder GW2EliteInsights program is looking at it works as intended and auto loads and then auto parses the file. Only files created by ArchDPS dose not seem to auto load. I do have 'Use NPC Name in EVTC save path' ticked and I have the program looking at the main folder that all the boss sub folders are stored.

**Comment by EliphasNUIT** [comment] 2020-08-28 19:08
I haven't been able to reproduce your problem, I have generated some golem logs and EI picked them up fine. I also use EI's auto parse functionality for my weekly clears for 2 years now and have yet to see the problem you are describing. So I have some questions:
- Did it ever work for you?
- Anything that could be interfering? 
- Do you have compression enabled on ArcDPS? If yes, does it work if you disable it?
- Can you link the .conf file here? You can generate one by opening the settings panel and saving your settings. That'll save a .conf file.

Thanks.

**Comment by NekoSojo** [comment] 2020-08-28 19:27
I have not been able to get it to work on its own. I have to copy the file in location or move it before the program finds it. I have attached a zip file with both the GuildWars2EliteInsights Config file and my current ArcDPS INI file.
[Config Files.zip](https://github.com/baaron4/GW2-Elite-Insights-Parser/files/5143831/Config.Files.zip)

**Comment by EliphasNUIT** [comment] 2020-08-28 19:34
Thanks, I'll play around with your settings and try to reproduce.

I have removed your link, it contains a webhook url, you shouldn't go around sharing those publicly.

**Comment by BattleMage** [comment] 2021-01-13 21:41
This feature is not working for me, too. Tried on two systems, none is working.

Compression is disabled, use NPC names is enabled,

**Comment by EliphasNUIT** [comment] 2021-01-18 16:59
Do you have more information? Since the initial report I've personally tried 7 computers (3 desktops, 4 laptops, hdd and ssd) with a variety of arcdps options. I've also asked 6 persons to try to reproduce, 4 of them not already using this functionality. Sadly, to this day, the feature hasn't failed once and frankly I don't know where to look at.

Is your problem the same? Working for manually added files but not generated by arc dps? If it never works, make sure that EI has read authorization on the path. A very quick way to discard this hypothesis would be to run EI as admin.

**Comment by BattleMage** [comment] 2021-01-21 11:00
I tried different things now, all without success. Neither multiple restarts nor starting in admin mode made the parser aware of new logs.

I'll try to provide as much information as I can to make this reproducable:
- Windows 10 2004 - German
- ArcDps installed with [GW2 Addon Manager](https://github.com/fmmmlee/GW2-Addon-Manager)
- Logs are written to the default location within "My Documents"
- Logs are written with boss name as directories
- Elite Insights Parser shows the correct path as "watched" when starting

If you need any more details I'd be happy to provide them.

**Comment by EliphasNUIT** [comment] 2021-03-10 19:24
Unfortunately, to this day I can still not reproduce this. In the next release I'll add some traces to the methods around the new file listeners so that you can share them here. Hopefully that'll give me some clues as to what's going wrong.

**Comment by BattleMage** [comment] 2021-03-11 08:04
I don't know if that's any help. but the directory listener from [PlenBotLogUploader](https://github.com/HardstuckGuild/PlenBotLogUploader) works. Perhaps looking at the implementation differences helps, as it's also written in C#.

**Comment by feisty69** [comment] 2021-03-19 19:08
Easily reproducible.
When arcdps creates the '*.evtc' file its actually not an '*.evtc' file to begin with.
Its actually a file without a file name extension and once the file is done it is renamed to '*.evtc'
https://user-images.githubusercontent.com/15022613/111830806-c3975180-88ee-11eb-9b3b-ceb54b0bfc03.mp4
As shown in this video.


So to test this you can:
1. Create a log (example name 20210319-195015.evtc)
2. Move the log to your Desktop.
3. Rename the file to "20210319-195015" (without .evtc)
4. Move the renamed file back into the log folder.
5. Now rename it back to "20210319-195015.evtc" (when its already inside the log folder).
This file **WILL NOT** get detected by the parser.

Now you can test by:
1. Moving the '20210319-195015.evtc' to your Desktop.
2. Moving it back to the log folder.
This **WILL** get detected by the parser.

**Comment by EliphasNUIT** [comment] 2021-03-20 11:45
That I was able to reproduce, thanks, it is also an easy fix. However that scenario only happens when compression is disabled, with compression enabled arccpds generates a .tmp.zip file as temporary and that is being detected. I'm not 100% certain this fixes the initial problem where OP said that compression or no compression did not make any difference, so:
- Their problem is different
- Arcdps is unable to compress on their computer so the option does not make a difference

Regardless @feisty69 and @BattleMage's problem should be fixed in next. I'll close this after feedback from @NekoSojo .

**Comment by EliphasNUIT** [comment] 2021-04-06 15:35
@feisty69 @BattleMage @NekoSojo
Could you confirm that latest release fixes your problems? If yes, I'd like to close this issue.

Thanks.

**Comment by BattleMage** [comment] 2021-04-06 17:48
My problem is solved by this. Thanks!

**Comment by EliphasNUIT** [comment] 2021-05-01 17:46
I'm not getting any news regarding this issue. I'm closing it for now. Comment here if you think this issue needs to be re-opened.

**Closed by EliphasNUIT** 2021-05-01 17:46 UTC
Labels: to investigate, unreproducible
