### ISSUE TITLE
Golem: Average Condition uptime not showing on some logs

### ISSUE THREAD

**Issue by Quadellupine** [baaron4/GW2-Elite-Insights-Parser#57] opened 2018-06-23 14:25 UTC
Hey!

In an attempt to minmax confusion uptime and DPS on mirage, we used your tool to parse golem logs. They usually showed the amount of stacks of confusion the golem had on average.
However, in the actual benchmark log (lol) this function randomly stopped working.
The damage is also much lower than normal. The ingame meter shower ~34k as endnumber, the log only shows 27. 

Links to the bugged HTMLs and evtc (github wont let me upload):
https://cdn.discordapp.com/attachments/409691829311635457/460087331290873856/buggedconfusionhtml.html
460084805175083010

Link to a normal log for reference:
https://cdn.discordapp.com/attachments/409691829311635457/460087362056093696/20180623-155523.evtc.zip
https://cdn.discordapp.com/attachments/409691829311635457/460087666092933150/20180623-155523.evtc.zip__fail.html

I'm not sure if this issue is arc or parser related, hence why I wanted to make that post and ask.

**Comment by EliphasNUIT** [comment] 2018-06-23 14:31
This does not look like a confusion bug, in the bugued log Tolgon does not have any power damage xD

**Comment by EliphasNUIT** [comment] 2018-06-23 14:36
Which version did you use? A previous version had issues.
This is what I'm getting in my branch:
![test2](https://user-images.githubusercontent.com/16018765/41810730-7fcf9cf0-7703-11e8-8c11-f8e2140325e0.png)
![test3](https://user-images.githubusercontent.com/16018765/41810731-8131de0a-7703-11e8-9add-16285eb6b67b.png)

**Comment by baaron4** [comment] 2018-06-23 14:47
That file name ending in .evtc.zip__fail.html makes me think this is indeed a older version of EI

**Comment by Quadellupine** [comment] 2018-06-23 15:14
I didn't update to the version released 13h ago, for some reason I didn't get a notifcation. The part that was weird to me was that all other (And it were many) previous golem logs worked, just not this one in particular.

**Comment by Quadellupine** [comment] 2018-06-23 15:19
Update, parsing it with the updated version causes the command line to throw errors and close before I can read them. It also errors "while performing background operations" if I open it in the exe. 
![image](https://user-images.githubusercontent.com/38409477/41811101-7f9e0da6-7709-11e8-9f0f-eecb642818f8.png) 
![image](https://user-images.githubusercontent.com/38409477/41811104-906fc228-7709-11e8-8ee6-235b3d5e6670.png)

Am I just dumb?

**Comment by EliphasNUIT** [comment] 2018-06-23 15:20
I'll fix that ASAP, we had a major rework as to how the application works, that must be the cause

**Comment by Quadellupine** [comment] 2018-06-23 15:28
https://cdn.discordapp.com/attachments/409691829311635457/460084805175083008/20180623-161059.evtc.zip

This is the bugged log I tried to parse

**Comment by EliphasNUIT** [comment] 2018-06-23 15:34
This is a golem right? seems like there is a regression on its death time, apparently you have been fighting it for 292471208 years. The application did not like that. Investigating

**Comment by Quadellupine** [comment] 2018-06-23 15:41
He did say it felt like it took that long lol

**Comment by EliphasNUIT** [comment] 2018-06-23 15:59
Was there an issue during the logging process? I'm seeing stuff that shouldn't be possible:
- There are two different golems
- One receives all the condi damage
- The other receives all the power damage
I've checked with raid heroes, it also has the same issue, the damage is split between 2 golems

**Comment by Tolgon** [comment] 2018-06-23 16:03
Here is the video of the whole fight.
https://www.youtube.com/watch?v=YSO3_dXm4EI

**Comment by EliphasNUIT** [comment] 2018-06-23 16:16
100% Arc dps issue, if you check your vid you can see that you are at 27Kish boss dps and 33Kish total dps

That would explain why at first GW2El did not detect the golem, to fix the detection I had to change the detection algorithm Delta advises to use at https://www.deltaconnected.com/arcdps/evtc/README.txt .

I'm not sure if I should push that fix now.

**Comment by Quadellupine** [comment] 2018-06-23 16:33
Not sure, as in it might break something else?

**Comment by EliphasNUIT** [comment] 2018-06-23 16:38
Yes, because it is kinda hacky ^^ And even if I did you'd never get all the data you'd like to, it is impossible to properly detect applied conditions in this log

**Comment by EliphasNUIT** [comment] 2018-06-23 17:49
There you go:
![t1](https://user-images.githubusercontent.com/16018765/41812178-80b391ec-771e-11e8-83db-5c05909b8ccf.png)
![t2](https://user-images.githubusercontent.com/16018765/41812179-81cbeb88-771e-11e8-904a-218d40deb4bd.png)

**Comment by Quadellupine** [comment] 2018-06-23 20:11
Thank you very much! I'll message delta about this issue later I guess.

**Comment by EliphasNUIT** [comment] 2018-06-23 20:39
I think we'll do another quick release soon. Please don't hesitate to come back if you see golem issues, i'm really not convinced that the hack covers everything ^^

**Comment by baaron4** [comment] 2018-06-23 22:03
You can always send files over Github just have to .zip them first.

**Comment by EliphasNUIT** [comment] 2018-06-23 22:21
Damnit Baroon, I'm try to attract people to GW2EI discord here! =D

**Comment by EliphasNUIT** [comment] 2018-06-28 10:56
Should be definitively fixed in next release. If not please re-open an issue =D

**Closed** 2018-06-28 10:56 UTC
Labels: bug
